# Java Maven CircleCI 2.0 configuration file
version: 2.1
executors:
  openjdk-8-executor:
    docker:
    - image: circleci/openjdk:8-jdk

jobs:
  build:
    executor: openjdk-8-executor

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx1g

    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: false

    # Download and cache dependencies
    - restore_cache:
        keys:
        - ranking-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - ranking-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: ranking-{{ checksum "pom.xml" }}

    # run tests!
    - run: mvn clean verify

    - store_test_results:
        path: target/surefire-reports